### ISSUE TITLE
How to create observable to use in Sequencit 

### ISSUE THREAD

**Issue by takaaptech** [Silphid/Silphid.Unity#2]
It is not an issue, it is just a question how to implelent a game using Sequencit:
I am a newbie on both Unirx and Sequencit so I wonder how to create Parallel and Sequence things in the real game:
I read the example included but still can not find the way to write real observable:

I have a level that has many waves, waves are in order (Sequence), next wave starts when current wave end.
Each wave has enemies that will spawn in parallel. Wave ends when all enemies died.
Enemy died when HP <= 0.

Can you have some demo code for Class: Level, Wave and Enemy?

Thank so much!

**Comment by Silphid** [comment]
Hello takaaptech,

If you are new to Rx, I recommend that you first familiarize yourself with it.  There are plenty of resources on the Net.  Here are my personal recommendations:

- [The introduction to Reactive Programming you've been missing](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754) - A great intro and overview. The place to start.
- [IntroToRx.com](introtorx.com) - The complete online version of a great book by Lee Campbell, very thorough and insightful.  But start with the previous link first! ;)
- [ReactiveX.io](reactivex.io) - The official reference hub for implementations of Rx on all platforms.
- [RxMarbles](rxmarbles.com) - Interactive diagrams to experiment with and better understand observables and their various operators.
- [UniRx](https://github.com/neuecc/UniRx) - Obviously, the UniRx documentation is another good read, with many good examples specific to Unity.

The thing to keep in mind when working with Sequencit is that you should create all your sequencing building blocks as `IObservable<Unit>` objects (or any type that implements that interface, such as `Sequence`, `Parallel` and `Lapse`).  The `Unit` type is used in UniRx when you don't care about transferring data in your observable and only want to use the observable to track the completion of something.  For example, you could create a method that creates and tracks one wave of enemies:

``` c#
private IObservable<Unit> SpawnWave(int numberOfEnemies, float difficultyLevel)
{
    // ...
}
```

The observable returned by that method allows to track when the wave has been completed (that is, when the observable completes, it means all enemies in the wave have been killed).

Then you could sequence multiple waves like so:

``` c#
private IObservable<Unit> SpawnAllWaves()
{
    return Sequence.Create(seq =>
    {
        seq.Add(SpawnWave(10, 1.0f));
        seq.Add(SpawnWave(15, 1.5f));
        seq.Add(SpawnWave(20, 2.5f));
    });
}
```

Now, each enemy's life-time could also be tracked by an `IObservable<Unit>`. Sequencit provides a simple class for that, named `Lapse` (make sure to pull the latest version of the "0.99" branch, because I just updated it). A `Lapse` is an `IObservable<Unit>` that completes when you dispose it. So you could dispose it when the enemy is killed (when its game object is destroyed):

``` c#
public GameObject EnemyPrefab;

private IObservable<Unit> SpawnEnemy(float delayInSeconds, float difficultyLevel)
{
    return Sequence.Create(seq =>
    {
        // So that enemies are spawned after different delays
        seq.AddInterval(delayInSeconds);

        seq.AddLapse(disposable =>
        {
            // Note: This lambda is invoked only once we reach that step in the sequence

            // Spawn enemy game object
            var enemy = EnemyPrefab.Instantiate();

            // TODO: Adjust enemy's hit points according to difficulty level

            // This attaches the lapse's disposable to the enemy's game object.
            // When the game object is destroyed (the enemy is killed), it automatically
            // disposes the lapse (and it will complete).
            disposable.AddTo(enemy);
        });
    });
}
```

Now, we could implement the `SpawnWave()` method with a `Parallel` (which is also an `IObservable<Unit>`):

``` c#
private IObservable<Unit> SpawnWave(int numberOfEnemies, float difficultyLevel)
{
    return Parallel.Create(para =>
    {
        for (int i = 0; i < numberOfEnemies; i++)
        {
            var delayInSeconds = i * 2f; // TODO: This could be randomized
            para.Add(SpawnEnemy(delayInSeconds, difficultyLevel));
        }
    });
}
```

Finally, don't forget to subscribe to your resulting observable, because otherwise nothing will happen. It is the subscription that triggers everything:

``` c#
var disposable = SpawnAllWaves().Subscribe();
```

If you want to detect when the player completed all waves you can do it the standard Rx way:

``` c#
var disposable = SpawnAllWaves().Subscribe(_ => {}, () => Debug.Log("All waves completed!"));
```

Or the Sequencit way:

``` c#
var disposable = Sequence.Start(seq => {
    seq.Add(SpawnAllWaves);
    seq.AddAction(() => Debug.Log("All waves completed!"));
});
```

Note the difference between `Sequence.Create()` and `Sequence.Start()`.  The first one, `Create()` only creates the observable and returns it; you can then subscribe to it or composite it with other observables.  The second one, `Start()`, creates the observable, subscribes to it (which triggers the sequencing of everything it contains) and returns the subscription's disposable.

I have not tested any of the above code, but it should be close to reality.

Good luck! :)
Mathieu

**Comment by takaaptech** [comment]
Hi @Silphid !
I know you really busy with this library, so much awesome features are being updated!
So thank for spending time for me. Thank so much for detail comment, I love it so much and I can understand completely your code.
For Enemy, I will be using Pool System instead of Instantiate, so when Enemy die, I will call something like Exit function (not Destroy), so how can I use disposable of Lapse here? 
Thank so much!

**Comment by Silphid** [comment]
Great, thanks for your appreciation!

The only thing that `disposable.AddTo(enemy)` really does is registering an event handler for when `enemy` is destroyed that calls `disposable.Dispose()`. So the only thing you need to do is to have some event on your enemy that is triggered when the enemy dies and then call `disposable.Disposable()` manually.

```c#
seq.AddLapse(disposable =>
{
  // Spawn enemy game object and retrieve Enemy component on it
  Enemy enemy = ...
  
  enemy.Died += () => disposable.Dispose();
});
```

Or better yet, declare the `Lapse` directly within your `Enemy` script to track the enemy's lifetime and expose it as an `IObservable<Unit>` to the outside world:

```c#
public class Enemy : MonoBehaviour
{
  private readonly Lapse _lifetime = new Lapse();
  public IObservable<Unit> Lifetime => _lifetime; // C# 6 or { get { return _lifeTime; } } in C# 4
  
  public void Kill()
  {
    _lifetime.Dispose();
  }
}
```

And then you can use the very clean syntax in your sequence:

```c#
seq.Add(() =>
{
  // Spawn enemy game object and retrieve Enemy component on it
  Enemy enemy = ...
  
  return enemy.Lifetime;
});
```
Note that here I replaced `seq.AddLapse()` with `seq.Add()`, which expects an `IObservable<Unit>` to be returned by the lambda (in this case `enemy.Lifetime`).

Hope this helps! :)

Regards,
Mathieu

**Comment by takaaptech** [comment]
Hi @Silphid !
 declare the Lapse directly within Enemy script is a great way! 
I see a (maybe) problem here ...
After call Kill with  _lifetime.Dispose();
Next time when I respawn an enemy that was called Kill before(the way pool system works), do i need re new _lifetime = new Lapse(); or some thing else?
Thank so much!

**Comment by Silphid** [comment]
Yes, you could recreate the `Lapse` in some `Resuscitate()` method.

**Comment by takaaptech** [comment]
Thank so much!
